### PR TITLE
Update screenshot asset link

### PR DESCRIPTION
**Pull request by joshbode**
- ~enable `WaylandWindowDecorations` feature for showing window-decorations~
- fix screenshot asset link to fix build

### CODE REVIEW

**Comment by joshbode** [comment]
Ugh - didn't see #162 - I'll remove the `WaylandWindowDecorations` addition and just keep the screenshot link update

**Review by travier — APPROVED** [review]
LGTM. Thanks.

**Comment by travier** [comment]
CC @hfiguiere

**Comment by joshbode** [comment]
Thanks!

**Pull request merged**
