### PR TITLE
Update to 4.1.1

### PR DESCRIPTION
**Pull request by cho2**
Update to 4.1.1

### CODE REVIEW

**Comment by cho2** [comment]
cc: @FakeShemp

**Comment by snaggen** [comment]
Did anyone actually test this build? Since it no longer seems to work? 
https://github.com/flathub/com.slack.Slack/issues/61

**Comment by bilelmoussaoui** [comment]
@snaggen Reverted

**Comment by cho2** [comment]
My bad, I'm running the wrong version while test it. :(

**Comment by FakeShemp** [comment]
I've done that _so_ many times XD

**Pull request merged**
