### PR TITLE
Update to 4.2.0

### PR DESCRIPTION
**Pull request by cho2**
Update to 4.2.0

### CODE REVIEW

**Comment by cho2** [comment]
test #67 + #68

**Comment by cho2** [comment]
Cuplikan layar dari 2019-12-06 06-36-46

**Comment by lasombra** [comment]
> Build [12278 successful](https://flathub.org/builds/#/builders/32/builds/12278)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/11717/com.slack.Slack.flatpakref
> ```

```
$ flatpak install --user https://dl.flathub.org/build-repo/11717/com.slack.Slack.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/11717/com.slack.Slack.flatpakref: Server returned status 404: Not Found
```

**Comment by FakeShemp** [comment]
I think zypak need to be called also, like `exec env TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/bin/slack \"$@\"`, but not sure if it'll work like it should.

**Comment by refi64** [comment]
This is working fine over here, are you sure it's not a local issue? Can you `rm -rf ~/.var/app/com.slack.Slack` and try running it again?

BTW please feel free to ping me if you think something is up with Zypak, when all the other similar PRs were merged I never realized this hadn't been fixed yet and was unaware this PR had been created.

**Comment by cho2** [comment]
bot build

**Comment by wjt** [comment]
This works on my machine, but it produces a vast amount of debug output while it runs. Is something accidentally turning on verbose logging from Slack? The version currently published on the `master` branch (this PR targets `beta`) does not produce so much output.

**Pull request closed without merging**
