### PR TITLE
Update to 4.3.2

### PR DESCRIPTION
**Pull request by cho2**
Update to 4.3.2

### CODE REVIEW

**Comment by cho2** [comment]
```
flatpak run com.slack.Slack     
[2:0205/113258.888092:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/lib/slack/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by refi64** [comment]
This version isn't using zypak like the beta branch...

**Comment by cho2** [comment]
When will the beta merged into master?

https://github.com/flathub/com.slack.Slack/pull/72 4.3.2 already merged

**Comment by cho2** [comment]
4.3.2 landed in master

**Pull request closed without merging**
