### PR TITLE
Update runtime to 19.08

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
bot, build

**Comment by TingPing** [comment]
I think this will solve it: https://github.com/flathub/buildbot-config/pull/68

**Comment by FakeShemp** [comment]
bot, build

**Comment by TingPing** [comment]
Sorry the PR was merged but the buildbot has to be redeployed, should happen by tomorrow :crossed_fingers:

**Comment by FakeShemp** [comment]
Let's try once more :)

bot, build

**Comment by FakeShemp** [comment]
bot, build

**Comment by TingPing** [comment]
Lets try after this - https://flathub.org/builds/#/builders/32/builds/8855

**Comment by FakeShemp** [comment]
bot, build

**Pull request merged**
